name: wiredash
description: Wiredash is an interactive user feedback tool for Flutter apps.
version: 1.0.0-alpha.6
homepage: https://wiredash.io
repository: https://github.com/wiredashio/wiredash-sdk

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  collection: ">=1.15.0 <2.0.0"
  file: ">=6.0.0-0 <7.0.0"
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ">=0.13.0-0 <0.15.0"
  http_parser: ">=4.0.0-0 <5.0.0"
  path_provider: ">=2.0.0 <3.0.0"
  shared_preferences: '>=2.0.0 <3.0.0'

dev_dependencies:
  fake_async: any
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
  test: any
  transparent_image: ^2.0.0

flutter:
  assets:
    - packages/wiredash/assets/images/logo_footer.png
    - packages/wiredash/assets/images/logo_grey.png
    - packages/wiredash/assets/images/logo_white.png
    - packages/wiredash/assets/images/pen.png

  plugin:
    platforms:
      android:
        default_package: wiredash
      ios:
        default_package: wiredash
      linux:
        default_package: wiredash
      macos:
        default_package: wiredash
      web:
        default_package: wiredash
      windows:
        default_package: wiredash

  fonts:
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter-Regular.ttf
        - weight: 400
        - asset: lib/assets/fonts/Inter-SemiBold.ttf
        - weight: 600
        - asset: lib/assets/fonts/Inter-Bold.ttf
        - weight: 700
    - family: Wirecons
      fonts:
        - asset: lib/assets/fonts/Wirecons.ttf
